# Generated by Django 6.1.1 on 2026-09-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0002_alter_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='baseline_workload_percent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
